### ISSUE TITLE
add iscsi support

### ISSUE THREAD

**Issue by dcpc007** [ryan-mcd/k3s-containers#3]
Hi, 

With my k3d test and learning to create a home cluster, i found your images in k3d issues.

But now, with my NAS, i have to use iscsi volume above NFS (too lazy with rights managements...).
at first time i installed open-iscsi on my host, but it's not enough ... pods use the virtual contenairized node :)

Then, is it possible to add it, or create another image nfs+iscsi ?
i try to make a quick one at home (nothing automated still), and maybe better if you keep it while more known than me :)

**Comment by dcpc007** [comment]
if needed, i'm on the discord Kubernetes @home (Telkar)

**Comment by ryan-mcd** [comment]
Unfortunately, I don't plan on adding any block storage options to these containers.

k3d is intended to run on a single host, and local-path achieves block storage requirements in this environment.

**Comment by dcpc007** [comment]
Ok, understand, i'll continue to learn a little on k3d and switch on k3s quicker than excpeted to start run my home apps.

I'm looking if possible to fire a k3d on the same linux where i'll have my k3s already running

For info i try to clone you Dockerfile to add it, it's more complicated than NFS.
lacks paths, and after modules not loaded, and again other problems to solve....
You can close then.
